# Generated by Django 5.0.5 on 2024-05-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=200, verbose_name='Содержание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Дата',
            },
        ),
        migrations.CreateModel(
            name='Blogers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('header_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloger.blodpost', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Дата',
            },
        ),
    ]
