# Generated by Django 5.0.5 on 2024-05-07 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0002_alter_blodpost_options_alter_blogers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
