# Generated by Django 5.0.5 on 2024-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0003_blogers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogers',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
