# Generated by Django 5.0.5 on 2024-05-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0004_alter_blogers_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogers',
            old_name='header_comm',
            new_name='post',
        ),
    ]
