# Generated by Django 5.0.5 on 2024-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0005_rename_header_comm_blogers_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blodpost',
            name='first_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
